# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Production dependencies - triggers semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 10
    ignore:
      # Ignore test dependencies in this update group
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "org.junit.platform:*"
      - dependency-name: "org.pitest:*"
      - dependency-name: "org.hamcrest:*"
      - dependency-name: "org.jeasy:*"
      - dependency-name: "io.mockk:*"
      - dependency-name: "org.apache.commons:commons-lang3"
      - dependency-name: "io.zipkin.brave:*"
      - dependency-name: "org.springframework.boot:spring-boot-starter-test"
      - dependency-name: "org.springframework.boot:spring-boot-starter-web"
      - dependency-name: "org.springframework.boot:spring-boot-starter-data-mongodb"
      - dependency-name: "org.springframework.boot:spring-boot-starter-data-jpa"
      - dependency-name: "org.springframework.boot:spring-boot-starter-amqp"
      - dependency-name: "de.flapdoodle.embed:*"
      - dependency-name: "com.github.fridujo:*"
      - dependency-name: "org.awaitility:*"
      - dependency-name: "com.github.tomakehurst:*"
      - dependency-name: "org.testcontainers:*"
      - dependency-name: "org.postgresql:*"
      - dependency-name: "com.zaxxer:HikariCP"
      - dependency-name: "org.springframework.cloud:spring-cloud-sleuth-*"
      - dependency-name: "org.springframework.cloud:spring-cloud-starter-openfeign"
      - dependency-name: "com.fasterxml.jackson.*:*"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-connector"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-mongodb-connector"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-postgres-connector"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-http-connector"
      - dependency-name: "io.github.lsd-consulting:lsd-junit5"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-generator"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-generator-ui-api"
      - dependency-name: "io.github.lsd-consulting:lsd-distributed-generator-ui-service"
      - dependency-name: "io.github.lsd-consulting:lsd-logging-library"
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"
        update-types:
          - "minor"
          - "patch"

      spring-dependencies:
        patterns:
          - "org.springframework.*:*"
        update-types:
          - "minor"
          - "patch"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
        update-types:
          - "minor"
          - "patch"

  # Test dependencies - does not trigger semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test"  # Does not trigger semantic release
    open-pull-requests-limit: 5
    groups:
      testing-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.junit.platform:*"
          - "org.pitest:*"
          - "org.hamcrest:*"
          - "org.jeasy:*"
          - "io.mockk:*"
          - "org.apache.commons:commons-lang3"
          - "io.zipkin.brave:*"
          - "org.springframework.boot:spring-boot-starter-test"
          - "org.springframework.boot:spring-boot-starter-web"
          - "org.springframework.boot:spring-boot-starter-data-mongodb"
          - "org.springframework.boot:spring-boot-starter-data-jpa"
          - "org.springframework.boot:spring-boot-starter-amqp"
          - "de.flapdoodle.embed:*"
          - "com.github.fridujo:*"
          - "org.awaitility:*"
          - "com.github.tomakehurst:*"
          - "org.testcontainers:*"
          - "org.postgresql:*"
          - "com.zaxxer:HikariCP"
          - "org.springframework.cloud:spring-cloud-sleuth-*"
          - "org.springframework.cloud:spring-cloud-starter-openfeign"
          - "com.fasterxml.jackson.*:*"
        update-types:
          - "minor"
          - "patch"
      
      lsd-test-dependencies:
        patterns:
          - "io.github.lsd-consulting:lsd-distributed-connector"
          - "io.github.lsd-consulting:lsd-distributed-mongodb-connector"
          - "io.github.lsd-consulting:lsd-distributed-postgres-connector"
          - "io.github.lsd-consulting:lsd-distributed-http-connector"
          - "io.github.lsd-consulting:lsd-junit5"
          - "io.github.lsd-consulting:lsd-distributed-generator"
          - "io.github.lsd-consulting:lsd-distributed-generator-ui-api"
          - "io.github.lsd-consulting:lsd-distributed-generator-ui-service"
          - "io.github.lsd-consulting:lsd-logging-library"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact
